const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { buildWorker } = require('../scripts/access-expired/build.cjs');

(async () => {
  const output = fs.mkdtempSync(path.join(os.tmpdir(), 'intoch-expiration-test-'));
  const { default: worker } = await import(pathToFileURL(buildWorker(output)).href);
  const originalFetch = global.fetch;
  global.fetch = () => { throw new Error('Suspension must never forward a request'); };
  try {
    for (const pathname of ['/', '/reserve.html', '/invoice-view.html?token=test', '/nested/guest/link', '/js/app.js']) {
      for (const method of ['GET', 'POST', 'HEAD', 'OPTIONS']) {
        const response = worker.fetch(new Request(`https://djiwana.intoch.app${pathname}`, { method }));
        assert.equal(response.status, 403);
        assert.equal(response.headers.get('cache-control'), 'no-store');
        assert.match(response.headers.get('content-type'), /text\/html/);
        assert.match(response.headers.get('content-security-policy'), /img-src data:/);
        assert.equal(response.headers.get('access-control-allow-origin'), null);
        const body = await response.text();
        if (method === 'HEAD') {
          assert.equal(body, '');
        } else {
          assert.match(body, /Your access has expired/);
          assert.match(body, /https:\/\/wa\.me\/6281325063362\?/);
          assert.match(body, /src="data:image\/png;base64,/);
          assert.doesNotMatch(body, /src="assets\/|<script/i);
        }
      }
    }
    console.log('Access expiration Worker: 20 route/method cases passed; embedded logo, contact and response headers verified.');
  } finally {
    global.fetch = originalFetch;
    // Keep temporary output available for inspection; no repository files are generated by this test.
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
