const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const form = fs.readFileSync('reserve.template.html','utf8').replace(/\r\n/g,'\n');
const app = fs.readFileSync('js/app.js','utf8').replace(/\r\n/g,'\n');
const dom = new JSDOM('<input id="f-date" value="2026-10-01"><input id="f-time"><input id="pax-value" value="10"><div id="time-pills"></div><input id="res-exclusive-area" type="checkbox"><input id="res-end-time" type="time"><input id="res-block-buffer" type="number"><input id="res-duration" type="number" value="180">',{runScripts:'outside-only'});
const w=dom.window;
w.$=id=>w.document.getElementById(id); w.gt=s=>s; w.gtf=s=>s; w.t=s=>s;
w.toast=()=>{}; w.showError=()=>{}; w.renderAreaCond=()=>{};
function extract(src,name,indent='') {
 const m=src.match(new RegExp('^'+indent+'(?:async )?function '+name+'\\([^]*?^'+indent+'}', 'm'));
 assert.ok(m,name); return m[0];
}
w.eval(`let AREA_SLOTS=[], AREA_BLOCK_DATE='', availabilityRequest=0;
let AREA_ID='outdoor', AVAIL={}, SHOW_CAPACITY=false;
let TIME_SLOTS=['12:00','13:00','14:00','15:00','16:00'], TIMES_EXPANDED=false;
const TIME_COLLAPSE_AT=8;
window.setArea=id=>{AREA_ID=id;};
`+['areaSlot','areaTimeBlocked','refreshBlockedTimes','setTime','renderTimePills','loadAvailability','readPaxRaw'].map(n=>extract(form,n,'      ')).join('\n')+'\n'+['readAreaBlock','timeToMinutes'].map(n=>extract(app,n)).join('\n'));
const slots = (remaining=25, exclusive=false) => ['12:00','13:00','14:00','15:00','16:00'].map(time=>({area_id:'outdoor',slot_time:time+':00',available_pax:time==='16:00'?65:remaining,total_capacity:65,exclusive_block:time!=='16:00'&&exclusive,duration_minutes:180}));
(async()=>{
 const calls=[];
 w.db={rpc:async name=>{calls.push(name);return {data:slots()};}};
 await w.loadAvailability();
 assert.deepEqual(calls,['area_slot_availability'],'capacity loads with percentage display disabled');
 assert.equal(w.areaTimeBlocked('13:00'),false,'party of 10 fits 25 remaining seats');
 w.$('f-time').value='13:00'; w.$('pax-value').value='30'; w.refreshBlockedTimes();
 assert.equal(w.$('f-time').value,'13:00','increasing pax keeps the waitlist selection');
 assert.equal(w.areaTimeBlocked('13:00'),true);
 assert.equal(w.areaTimeBlocked('16:00'),false);
 assert.ok(Array.from(w.document.querySelectorAll('button')).some(b=>!b.disabled&&b.textContent==='13:00 - Waitlist'));
 w.$('pax-value').value='25'; w.refreshBlockedTimes(); assert.equal(w.areaTimeBlocked('13:00'),false,'exact fit allowed');
 w.setArea('indoor'); w.refreshBlockedTimes(); assert.equal(w.document.querySelectorAll('button:disabled').length,0,'other area unaffected');
 w.setArea('outdoor'); w.db.rpc=async()=>({data:slots(0,true)}); await w.loadAvailability();
 assert.equal(w.areaTimeBlocked('13:00'),true,'exclusive hold blocks every party');
 assert.ok(Array.from(w.document.querySelectorAll('button')).some(b=>!b.disabled&&b.textContent==='13:00 - Waitlist'));
 w.$('f-date').value='2026-10-02'; assert.equal(w.areaTimeBlocked('13:00'),false,'old-date data never blocks new date');
 const pending=[]; w.db.rpc=()=>new Promise(resolve=>pending.push(resolve));
 const old=w.loadAvailability(); w.$('f-date').value='2026-10-03'; const current=w.loadAvailability();
 pending[1]({data:slots(65)}); await current; pending[0]({data:slots(0,true)}); await old;
 assert.equal(w.areaTimeBlocked('13:00'),false,'late response cannot overwrite new date');
 let failed=false; w.showError=()=>{failed=true;}; w.db.rpc=async()=>({error:new Error('offline')});
 await w.loadAvailability(); assert.equal(failed,true);
 w.$('res-end-time').value='16:00'; w.$('res-block-buffer').value='30';
 const block=w.readAreaBlock('res','outdoor','13:00');
 assert.deepEqual(JSON.parse(JSON.stringify(block)),{exclusive_area:false,end_time:'16:00',block_buffer_minutes:30,booking_duration_minutes:180},'partial hold preserves end time and buffer');
 w.$('res-exclusive-area').checked=true; assert.equal(w.readAreaBlock('res',null,'13:00'),null);
 w.$('res-end-time').value='12:00'; assert.equal(w.readAreaBlock('res','outdoor','13:00'),null);
 w.$('res-end-time').value='16:00'; w.$('res-block-buffer').value='800'; assert.equal(w.readAreaBlock('res','outdoor','13:00'),null);
 w.$('res-block-buffer').value='1.5'; assert.equal(w.readAreaBlock('res','outdoor','13:00'),null);
 w.$('res-block-buffer').value='30'; w.$('res-duration').value='0'; assert.equal(w.readAreaBlock('res','outdoor','13:00'),null);
 w.$('res-duration').value='120'; w.$('res-exclusive-area').checked=false; w.$('res-end-time').value='';
 assert.equal(w.readAreaBlock('res','outdoor','13:00').booking_duration_minutes,120);
 const sql=fs.readFileSync('migrations/20260909_timed_table_capacity.sql','utf8').replace(/\r\n/g,'\n');
 assert.ok(fs.readFileSync('migrations/ALL_IN_ONE.sql','utf8').replace(/\r\n/g,'\n').includes(sql));
 console.log('Timed-slot form: exact fit, pax changes, area/date changes, exclusive blocks, stale responses, duration and buffer validation passed');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>w.close());
