const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const form = fs.readFileSync('reserve.template.html', 'utf8').replace(/\r\n/g, '\n');
const app = fs.readFileSync('js/app.js', 'utf8').replace(/\r\n/g, '\n');
const sql = fs.readFileSync('migrations/20260908_area_time_blocks.sql', 'utf8');
const dom = new JSDOM('<input id="f-date" value="2026-10-01"><input id="f-time"><div id="time-pills"></div><input id="res-exclusive-area" type="checkbox"><input id="res-end-time" type="time"><input id="res-block-buffer" type="number">', { runScripts: 'outside-only' });
const w = dom.window;
w.$ = id => w.document.getElementById(id);
w.gt = s => s;
w.gtf = s => s;
w.t = s => s;
w.toast = () => {};
w.showError = () => {};
w.renderAreaCond = () => {};
function extract(src, name, indent = '') {
  const found = src.match(new RegExp('^' + indent + '(?:async )?function ' + name + '\\([^]*?^' + indent + '}', 'm'));
  assert.ok(found, name);
  return found[0];
}
w.eval(`let AREA_BLOCKS = [], AREA_BLOCK_DATE = '', availabilityRequest = 0;
let AREA_ID = 'outdoor', AVAIL = {}, SHOW_CAPACITY = false;
let TIME_SLOTS = ['12:00','13:00','14:00','15:00','16:00'], TIMES_EXPANDED = false;
const TIME_COLLAPSE_AT = 8;
window.setArea = value => {AREA_ID = value;};
window.setBlockStart = value => {AREA_BLOCKS[0].block_start = value;};
` + ['areaTimeBlocked','refreshBlockedTimes','setTime','renderTimePills','loadAvailability'].map(n => extract(form,n,'      ')).join('\n') + '\n' + ['readAreaBlock','timeToMinutes'].map(n => extract(app,n)).join('\n'));
(async () => {
  const calls = [];
  w.db = { rpc: async (name, args) => { calls.push(name); return {data: [{area_id:'outdoor',block_start:'13:00:00',block_end:'16:00:00'}]}; } };
  w.$('f-time').value = '14:00';
  await w.loadAvailability();
  assert.deepEqual(calls, ['area_booking_blocks'], 'blocks load even when capacity display is disabled');
  assert.equal(w.$('f-time').value, '', 'blocked previous selection cleared');
  assert.deepEqual(Array.from(w.document.querySelectorAll('#time-pills button')).filter(b=>b.disabled).map(b=>b.textContent), ['13:00 - Full','14:00 - Full','15:00 - Full']);
  assert.equal(w.areaTimeBlocked('12:00'), false);
  assert.equal(w.areaTimeBlocked('16:00'), false, 'end boundary available');
  w.setArea('indoor'); w.refreshBlockedTimes();
  assert.equal(w.document.querySelectorAll('#time-pills button:disabled').length, 0, 'other area unaffected');
  w.setArea('outdoor'); w.setBlockStart('12:30:00');
  assert.equal(w.areaTimeBlocked('12:00'), false);
  assert.equal(w.areaTimeBlocked('12:30'), true, 'buffer boundary is inclusive');
  w.$('f-date').value = '2026-10-02';
  assert.equal(w.areaTimeBlocked('13:00'), false, 'old date cannot block a new date');
  const pending = [];
  w.db.rpc = () => new Promise(resolve => pending.push(resolve));
  const old = w.loadAvailability();
  w.$('f-date').value = '2026-10-03';
  const current = w.loadAvailability();
  pending[1]({data: []}); await current;
  pending[0]({data: [{area_id:'outdoor',block_start:'13:00:00',block_end:'16:00:00'}]}); await old;
  assert.equal(w.areaTimeBlocked('13:00'), false, 'slow old response cannot replace latest date');
  let errorShown = false;
  w.showError = () => {errorShown = true;};
  w.db.rpc = async () => ({error: new Error('offline')});
  await w.loadAvailability(); assert.equal(errorShown, true, 'failed RPC is reported');
  w.$('res-exclusive-area').checked = true;
  w.$('res-end-time').value = '16:00'; w.$('res-block-buffer').value = '30';
  assert.deepEqual(JSON.parse(JSON.stringify(w.readAreaBlock('res','outdoor','13:00'))), {exclusive_area:true,end_time:'16:00',block_buffer_minutes:30});
  assert.equal(w.readAreaBlock('res',null,'13:00'), null);
  w.$('res-end-time').value = '12:00'; assert.equal(w.readAreaBlock('res','outdoor','13:00'), null);
  w.$('res-end-time').value = '16:00'; w.$('res-block-buffer').value = '800';
  assert.equal(w.readAreaBlock('res','outdoor','13:00'), null, 'buffer cannot cross midnight');
  w.$('res-block-buffer').value = '-1'; assert.equal(w.readAreaBlock('res','outdoor','13:00'), null);
  w.$('res-block-buffer').value = '1.5'; assert.equal(w.readAreaBlock('res','outdoor','13:00'), null);
  w.$('res-exclusive-area').checked = false;
  assert.equal(w.readAreaBlock('res','outdoor','13:00').block_buffer_minutes, 0);
  const publicFn = sql.slice(sql.indexOf('create or replace function public.create_public_reservation'));
  assert.ok(publicFn.indexOf('pg_advisory_xact_lock') < publicFn.indexOf('insert into guests'));
  assert.match(publicFn, /p_time >= b\.block_start and p_time < b\.block_end/);
  assert.match(publicFn, /and not r\.exclusive_area/);
  const availability = sql.slice(sql.indexOf('create or replace function public.area_availability'),sql.indexOf('create or replace function public.create_public_reservation'));
  assert.match(availability,/and not r\.exclusive_area/, 'exclusive event excluded from all-day estimate');
  assert.match(sql, /r\.id is distinct from new\.id/);
  assert.match(sql, /status in \('Reserved','Confirmed','Incoming','Arrived'\)/);
  assert.match(sql, /create trigger reservations_z_guard_area_block/);
  assert.match(sql, /returns table\(area_id uuid, block_start time without time zone, block_end time without time zone\)/);
  assert.ok(fs.readFileSync('migrations/ALL_IN_ONE.sql','utf8').replace(/\r\n/g,'\n').endsWith(sql.replace(/\r\n/g,'\n')), 'standalone migration matches combined file');
  console.log('Area blocks: boundaries, buffer, date/area changes, stale responses, validation and SQL guard contracts passed');
})().catch(e => {console.error(e);process.exitCode=1;}).finally(()=>w.close());
