const assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const fixture=require('../scripts/demo-booking-fixture.cjs');
const {source}=require('../scripts/demo-tour-fixture.cjs');
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function harness(context='staff',previous=null,options={}) {
 const errors=[],console=new VirtualConsole();console.on('jsdomError',error=>{if(!error.message.includes('navigation'))errors.push(error);});console.on('error',value=>errors.push(value));
 const html=context==='staff'?fixture.staffHtml():context==='form'?fixture.formHtml():fixture.createdHtml();
 const dom=new JSDOM(html,{url:(options.origin||'http://127.0.0.1:8080')+(context==='staff'?'/':context==='form'?'/reserve.html':'/reservation-created.html'),runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:console});
 const win=dom.window;
 win.matchMedia=query=>({matches:query.includes('reduce')||query.includes('640px')&&!!options.mobile});win.scrollTo=()=>{};win.HTMLElement.prototype.scrollIntoView=function(){};
 win.HTMLElement.prototype.getBoundingClientRect=function(){const hidden=this.closest('.hidden')||(this.closest('.page-section')&&!this.closest('.page-section').classList.contains('active'));return {width:hidden?0:300,height:hidden?0:50,x:30,y:100,left:30,top:100,right:330,bottom:150};};
 if(previous){for(const [k,v] of Object.entries(previous.session))win.sessionStorage.setItem(k,v);for(const [k,v] of Object.entries(previous.local))win.localStorage.setItem(k,v);}
 const scripts=[];
 for(const script of win.document.querySelectorAll('script')){
  const src=script.getAttribute('src');
  if(src&&/^(assets\/vendor|js\/(demo|demo-tour|demo-tour-environment|demo-booking-tour)\.js)/.test(src))scripts.push(source(src.split('?')[0]));
  else if(!src)scripts.push(script.textContent);
 }
 win.eval(scripts.join(';\n')+';\n'+(options.setup||''));
 await sleep(100);
 const title=()=>win.document.querySelector('.intoch-online-tour .driver-popover-title')?.textContent;
 async function until(test,label='Expected booking UI'){for(let i=0;i<150;i++){if(test())return;await sleep(20);}throw Error(label+': '+title()+' '+errors.map(e=>e.message||e).join('\n'));}
 const click=selector=>{const node=win.document.querySelector(selector);assert.ok(node,selector);node.click();const handler=node.getAttribute('onclick');if(handler)new win.Function('event',handler).call(node,new win.Event('click'));};
 const input=(id,value)=>{const node=win.document.getElementById(id);node.value=value;node.dispatchEvent(new win.Event('input',{bubbles:true}));};
 const active=()=>JSON.parse(win.sessionStorage.getItem('intoch:online-demo:v1:https://hkrhsubhfqrgqkuhpvql.supabase.co:active'));
 const snapshot=()=>({session:Object.fromEntries(Object.keys(win.sessionStorage).map(k=>[k,win.sessionStorage.getItem(k)])),local:Object.fromEntries(Object.keys(win.localStorage).map(k=>[k,win.localStorage.getItem(k)]))});
 return {win,dom,errors,title,until,click,input,active,snapshot};
}
async function launch(){let h=await harness();await h.until(()=>h.win.document.getElementById('demo-online-guide'));h.click('#demo-online-guide');await h.until(()=>h.title()==='Book as a guest');assert.equal(h.win.document.querySelector('.driver-popover-next-btn').disabled,true);h.click('[data-booking-tour="form-link"]');const saved=h.snapshot();assert.equal(h.active().step,'name');h.dom.window.close();return saved;}
async function fill(saved){const h=await harness('form',saved);await h.until(()=>h.title()==='Introduce your demo guest');h.input('f-name','Wrong name');assert.equal(h.title(),'Introduce your demo guest');h.input('f-name',h.active().name);await h.until(()=>h.title()==='Use a fictional contact');h.input('f-phone',h.active().phone);await h.until(()=>h.title()==='Choose the party size');h.click('.driver-popover-next-btn');await h.until(()=>h.title()==='Choose an available visit');h.click('#time-pills button');await h.until(()=>h.title()==='Create the demo booking');assert.equal(h.win.localStorage.getItem('intoch-fixture-booking-writes'),null);return h;}
(async()=>{
 let h=await harness('form');await sleep(100);assert.equal(h.title(),undefined,'Normal public guests get no guide');h.dom.window.close();
 h=await harness('staff',null,{origin:'https://client.example'});assert.equal(h.win.document.getElementById('demo-online-guide'),null);h.dom.window.close();
 let saved=await launch();
 h=await harness('form',saved,{setup:'fixture.authValid=false;'});await sleep(120);assert.equal(h.title(),undefined);assert.equal(h.active(),null,'Unverified staff cannot activate form guide');h.dom.window.close();
 h=await fill(saved);h.win.fixture.delay=100;h.click('#btn-submit');await sleep(30);assert.equal(h.active().step,'submit','Server success is required');await h.until(()=>h.active()?.step==='saved');assert.equal(h.win.localStorage.getItem('intoch-fixture-booking-writes'),'1');assert.ok(h.active().reservationId);saved=h.snapshot();h.dom.window.close();
 h=await harness('created',saved);await h.until(()=>h.title()==='Read the booking outcome');assert.match(h.win.document.querySelector('.driver-popover-description').textContent,/booking is reserved/);assert.equal(h.win.document.querySelector('.driver-popover-prev-btn').disabled,true,'Back cannot replay a save');h.click('.driver-popover-next-btn');saved=h.snapshot();assert.equal(h.active().step,'online');h.dom.window.close();
 h=await harness('staff',saved,{mobile:true});await h.until(()=>h.title()==='See online bookings arrive');h.win.fixture.delay=100;h.click('[data-booking-tour="online-tab"]');await sleep(20);assert.equal(h.title(),'See online bookings arrive');await h.until(()=>h.title()==='Open your booking day');h.click('.driver-popover-prev-btn');await h.until(()=>h.title()==='See online bookings arrive');h.click('[data-booking-tour="online-tab"]');await h.until(()=>h.title()==='Open your booking day');h.click('[data-booking-tour="day"]');await h.until(()=>h.title()==="Your guest's booking is here");assert.equal(h.active().reservationId,h.win.document.querySelector('[data-booking-tour="row"]').dataset.bookingId);
 saved=h.snapshot();h.dom.window.close();h=await harness('staff',saved);await h.until(()=>h.win.document.querySelector('.demo-tour-dock'));h.click('.demo-tour-dock button');await h.until(()=>h.title()==="Your guest's booking is here",'Reload restores exact booking/day');h.click('.driver-popover-next-btn');await h.until(()=>h.title()==='Understand its status');h.click('.driver-popover-next-btn');await h.until(()=>h.title()==='Know what needs follow-up');h.click('.driver-popover-next-btn');await h.until(()=>h.title()==='Guest to front desk, connected');h.click('.driver-popover-next-btn');assert.equal(h.active(),null);assert.equal(h.win.localStorage.getItem('intoch-fixture-booking-writes'),'1');assert.equal(h.win.localStorage.getItem('intoch:online-demo:v1:https://hkrhsubhfqrgqkuhpvql.supabase.co:fixture-admin:seen'),'completed');h.dom.window.close();
 for(const status of ['Waitlist','Incoming']){
  h=await fill(await launch());h.win.fixture.bookingStatus=status;h.click('#btn-submit');await h.until(()=>h.active()?.step==='saved');saved=h.snapshot();h.dom.window.close();h=await harness('created',saved);await h.until(()=>h.title()==='Read the booking outcome');assert.match(h.win.document.querySelector('.driver-popover-description').textContent,status==='Waitlist'?/not a confirmed table/:/not yet confirmed/);h.dom.window.close();
 }
 h=await fill(await launch());h.input('f-phone','081234567890');h.click('#btn-submit');await h.until(()=>h.win.document.querySelector('.demo-tour-dock'));assert.equal(h.win.localStorage.getItem('intoch-fixture-booking-writes'),null,'Guide rejects nonfictional details');h.dom.window.close();
 h=await fill(await launch());h.win.fixture.rpcCode='time_full';h.click('#btn-submit');await sleep(100);assert.equal(h.active().step,'submit');assert.equal(h.active().submissionAttempted,false);assert.equal(h.win.localStorage.getItem('intoch-fixture-booking-writes'),null);h.win.fixture.rpcCode=null;h.click('#btn-submit');await h.until(()=>h.active()?.step==='saved');assert.equal(h.win.localStorage.getItem('intoch-fixture-booking-writes'),'1');h.dom.window.close();
 h=await fill(await launch());h.win.fixture.writeThenError=true;h.click('#btn-submit');await h.until(()=>h.win.document.querySelector('.demo-tour-dock'));assert.equal(h.active().submissionAttempted,true);saved=h.snapshot();h.dom.window.close();h=await harness('form',saved);await h.until(()=>h.win.document.querySelector('.demo-tour-dock'));assert.equal(h.title(),undefined,'Interrupted submission never automatically retries');h.win.eval("(()=>{const k='intoch:online-demo:v1:https://hkrhsubhfqrgqkuhpvql.supabase.co:active';const s=JSON.parse(sessionStorage.getItem(k));s.step='online';s.paused=true;sessionStorage.setItem(k,JSON.stringify(s));})()");saved=h.snapshot();h.dom.window.close();h=await harness('staff',saved);h.click('.demo-tour-dock button');await h.until(()=>h.title()==='See online bookings arrive','Recover committed result after lost response');assert.ok(h.active().reservationId);assert.equal(h.win.localStorage.getItem('intoch-fixture-booking-writes'),'1');h.win.fixture.fail='reservations';h.click('[data-booking-tour="online-tab"]');await h.until(()=>h.win.document.querySelector('.demo-tour-dock'));assert.equal(h.title(),undefined,'Failed read pauses');h.win.DemoBookingTour.teardown();assert.equal(h.active(),null);h.dom.window.close();
 h=await fill(await launch());h.win.fixture.signOut();assert.equal(h.title(),undefined);assert.equal(h.active(),null,'Auth logout tears down public guide');h.dom.window.close();
 console.log('Online reservation guide: real submit/overview/day/row handlers, fictional-only action gates, exact booking recovery, status copy, failed/uncertain saves, reads, auth and teardown passed.');
})().catch(error=>{console.error(error);process.exit(1);});
