const fs = require('fs');
const assert = require('node:assert/strict');
const app = fs.readFileSync('js/app.js','utf8');
const html = fs.readFileSync('index.html','utf8');
const reserve = fs.readFileSync('reserve.template.html','utf8');
const sql = fs.readFileSync('migrations/20260919_financial_tracking.sql','utf8');
assert.match(html,/id="page-settings-financial"/);
assert.match(html,/id="set-deposit-tracking"/);
assert.match(html,/id="set-spending-tracking"/);
assert.match(html,/finishVisitWithoutSpending\(\)/);
assert.match(app,/deposit_enabled !== false/);
assert.match(app,/spending_enabled !== false/);
assert.match(app,/\.update\(\{ value \}\)\.eq\("key", "financial_tracking"\)\.select\("value"\)/);
assert.match(reserve,/DEPOSIT_TRACKING_ENABLED && data\.deposit_required/);
assert.match(sql,/spend_recording_status in \('recorded','skipped'\)/);
assert.match(sql,/spend_amount=null[\s\S]*spend_recording_status='skipped'/);
assert.match(sql,/spend_recording_status='recorded'/);
assert.doesNotMatch(sql,/delete from public\.(visits|reservations|invoices|invoice_payments)/i);
console.log('Financial settings, compatibility, public deposit hiding, recorded zero and skipped spending checks passed');
