const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {PGlite} = require('@electric-sql/pglite');
const {JSDOM}=require('jsdom');
const invoice=fs.readFileSync('js/invoice.js','utf8');
const app=fs.readFileSync('js/app.js','utf8');
const wa=fs.readFileSync('js/wa.js','utf8');
const lift=(src,name)=>src.match(new RegExp('^(?:async )?function '+name+'\\([^]*?^}', 'm'))[0];
const ctx=vm.createContext({invParseNum:v=>v==null?null:Number(String(v).replace(/\D/g,'')),waTemplateBody:()=> 'Total: {jumlah}\n{invoice}',waGreetName:x=>x,WA_RESTAURANT_NAME:'Test',waRenderTemplate:(body,data)=>body.replace(/\{(\w+)\}/g,(_,k)=>data[k])});
vm.runInContext(lift(invoice,'invSummaryFrom')+'\n'+lift(wa,'waInvoiceMessage'),ctx);
const snap={total:'5.000.000',dp:'2.500.000',settle:'2.500.000',dpOn:true,settleOn:false};
assert.equal(ctx.invSummaryFrom(snap).amount_due,2500000);
assert.equal(ctx.invSummaryFrom({...snap,dpOn:false}).amount_due,5000000);
assert.equal(ctx.invSummaryFrom({...snap,settleOn:true,settle:'1.000.000'}).amount_due,1000000);
const message=ctx.waInvoiceMessage({amountText:'Rp 5.000.000',requestedText:'Rp 2.500.000',requestLabel:'Deposit (DP)',link:'https://demo.test/invoice'});
assert.match(message,/Total: Rp 5\.000\.000/);assert.match(message,/Deposit \(DP\): Rp 2\.500\.000 dari total Rp 5\.000\.000/);
const dom=new JSDOM('<input id="amount" type="text">',{runScripts:'outside-only'});
dom.window.eval(lift(app,'formatPaymentAmount'));
const input=dom.window.document.getElementById('amount');input.value='2500000';input.setSelectionRange(7,7);dom.window.formatPaymentAmount(input);assert.equal(input.value,'2.500.000');
input.value='-2500000';input.setSelectionRange(8,8);dom.window.formatPaymentAmount(input);assert.equal(input.value,'-2.500.000','refund sign is preserved');dom.window.close();
(async()=>{
 const db=new PGlite();try {
 await db.exec(`create table reservations(id uuid primary key,status text,deposit_required boolean,deposit_expected numeric,deleted_at timestamptz,updated_at timestamptz,reservation_date date,reservation_time time,deposit_due_at timestamptz);
 create table invoice_payments(id uuid default gen_random_uuid(),reservation_id uuid,amount numeric,paid_on date,method text,reference text,note text,recorded_by uuid);
 create table invoices(id uuid primary key default gen_random_uuid(),reservation_id uuid,kind text,status text,doc jsonb,total numeric,amount_due numeric,deposit_applied numeric,created_at timestamptz default now());
 insert into reservations values ('00000000-0000-0000-0000-000000000001','Waitlist',true,5000000,null,now(),current_date,'13:00',null);`);
 const id='00000000-0000-0000-0000-000000000001';
 await db.exec(fs.readFileSync('migrations/20260911_reservation_update_payment.sql','utf8'));
 await db.query("insert into invoices(reservation_id,kind,status,doc,total,amount_due) values($1,'deposit','issued',$2,5000000,5000000)",[id,JSON.stringify(snap)]);
 await db.query('insert into invoice_payments(reservation_id,amount) values($1,2500000)',[id]);
 const migration=fs.readFileSync('migrations/20260912_invoice_requested_deposit.sql','utf8');
 await db.exec(migration);await db.exec(migration);
 const booking=async()=>(await db.query('select * from reservations where id=$1',[id])).rows[0];
 assert.equal((await booking()).status,'Reserved','already-paid DP confirms even though full bill is unpaid');
 assert.equal(Number((await booking()).deposit_expected),2500000);
 assert.equal((await db.query('select count(*)::int as n from invoice_payments')).rows[0].n,1,'repair invents no payment');
 await db.exec("delete from invoice_payments; update reservations set status='Waitlist'; update invoices set doc=doc");
 assert.equal((await booking()).status,'Waitlist','invoice saving alone does not confirm');
 const pay=async amount=>(await db.query('select record_deposit_payment($1,$2,current_date) as result',[id,amount])).rows[0].result;
 assert.equal((await pay(1000000)).locked,false);
 assert.equal((await booking()).status,'Waitlist','partial deposit stays pending');
 assert.equal((await pay(1500000)).locked,true);
 assert.equal((await booking()).status,'Reserved','deposit paid over multiple records confirms');
 await db.query("update invoices set doc=$1",[JSON.stringify({...snap,dpOn:false})]);
 assert.equal(Number((await booking()).deposit_expected),5000000,'unchecked deposit requests full total');
 await db.query("insert into invoices(reservation_id,kind,status,doc,total) values($1,'settlement','issued',$2,5000000)",[id,JSON.stringify({...snap,settleOn:true})]);
 assert.equal(Number((await booking()).deposit_expected),5000000,'separate settlement never rewrites deposit requirement');
 assert.equal(Number((await db.query("select amount_due from invoices where kind='settlement'")).rows[0].amount_due),2500000);
 console.log('Requested amount: WhatsApp total/deposit, signed formatting, existing payment repair, invoice-only save and partial/full deposit transitions passed');
 }finally{await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
