const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const app = fs.readFileSync('js/app.js', 'utf8').replace(/\r\n/g,'\n');
const sql = fs.readFileSync('migrations/ALL_IN_ONE.sql', 'utf8');
const dom = new JSDOM(`<input id="res-table-id"><select id="res-area"><option value="a">Room A</option><option value="b">Room B</option></select><div id="res-table-picker"></div><select id="res-action-area"><option value="a">Room A</option><option value="b">Room B</option></select><div id="res-action-table-wrap"></div>`, {runScripts:'outside-only'});
const w = dom.window;
w.allAreas = [{id:'a',name:'Room A'},{id:'b',name:'Room B'}];
w.allTables = [{id:'t1',area_id:'a',name:'A1',is_active:true,capacity:4}, {id:'t2',area_id:'a',name:'A2',is_active:true,capacity:6}, {id:'t3',area_id:'a',name:'A3',is_active:true,capacity:4}, {id:'old',area_id:'a',name:'Archived',is_active:false}, {id:'b1',area_id:'b',name:'B1',is_active:true}];
w.tablePickerContext = {res:{skipOccupancy:false,occupiedIds:new Set(['t3'])},actions:{skipOccupancy:false,occupiedIds:new Set(['t3'])}};
w.t = s=>s;
w.toast = ()=>{};
w.escapeHtml = s => String(s).replace(/[<>&"']/g, '_');
w.updateResVipTimeRange = ()=>{};
w.isVipTableId = ()=>false;
w.loader = ()=>{};
w.hideModal = ()=>{};
w.loadReservations = ()=>{};
w.isViewingStaffDashboard = ()=>false;
w.TODAY = '2026-09-07';
const names = ['timeToMinutes','readAreaBlock','getTableById','assignedTableIds','tableSelectionIds','selectedTableIdsFor','assignedTableNames','renderTableSelection','selectTable','selectAllAreaTables','clearTableSelection','fetchOccupiedTableIds','renderResActionTableGrid','selectResActionTable','selectAllResActionTables','onResActionAreaChange','saveResActionTable'];
w.eval('let _resActionSelectedTables = []; let _resActionReservation = {id:"r1"};\n' + names.map(name => app.match(new RegExp('^(?:async )?function '+name+'\\([^]*?^}', 'm'))[0]).join('\n'));
const ids = () => Array.from(w.selectedTableIdsFor('res'));
(async () => {
  assert.deepEqual(Array.from(w.assignedTableIds({table_id:'t1'})), ['t1']);
  w.renderTableSelection('res',['t1']);
  w.selectTable('res','t2'); assert.deepEqual(ids(), ['t1','t2']);
  assert.equal(w.document.querySelectorAll('[aria-pressed="true"]').length,2);
  w.selectTable('res','t1'); assert.deepEqual(ids(), ['t2']);
  w.selectTable('res','b1'); assert.deepEqual(ids(), ['t2'], 'cannot mix rooms');
  w.selectAllAreaTables('res','a'); assert.deepEqual(ids(), ['t2','t1'], 'bulk selection skips occupied and archived tables');
  w.clearTableSelection('res'); assert.deepEqual(ids(), []);
  w.tablePickerContext.res.skipOccupancy = true;
  w.selectAllAreaTables('res','a'); assert.deepEqual(ids(), ['t1','t2','t3']);
  assert.equal(w.assignedTableNames({table_ids:ids()}), 'A1, A2, A3');
  w.renderTableSelection('res',['old']);
  assert.equal(w.document.querySelector('[data-table-id="old"]').disabled,false,'existing archived assignment can be removed');
  w.selectTable('res','old'); assert.deepEqual(ids(), []);
  w.renderResActionTableGrid('a',['t1']);
  w.selectResActionTable('t2');
  w.selectAllResActionTables();
  let payload;
  w.db = {from(){return {update(p){payload=p;return this},eq(){return this},select(){return Promise.resolve({data:[{id:'r1'}],error:null})}}}};
  w.supabaseQuery = fn=>fn();
  await w.saveResActionTable('r1');
  assert.deepEqual(Array.from(payload.table_ids),['t1','t2']);
  assert.equal(payload.table_id,'t1');
  w.document.getElementById('res-action-area').value='b';
  w.onResActionAreaChange('r1');
  await w.saveResActionTable('r1');
  assert.deepEqual(Array.from(payload.table_ids),[],'changing rooms clears previous selection');
  assert.equal(payload.table_id,null);
  // Occupancy includes secondary tables and excludes both sides of one's own arrival.
  w.db = {from(table){return {select(){return this},eq(){return this},neq(){return this},not(){return this},is(){return this},then(resolve){return Promise.resolve(resolve({data:table==='visits' ? [{id:'v1',reservation_id:'r1',table_ids:['t1','t2']},{id:'v2',table_ids:['t3','b1']}] : [{id:'r1',table_ids:['t1','t2']}]}))}}}};
  assert.deepEqual(Array.from(await w.fetchOccupiedTableIds('r1','reservation')).sort(), ['b1','t3']);
  assert.deepEqual(Array.from(await w.fetchOccupiedTableIds('v1','visit','r1')).sort(), ['b1','t3']);
  assert.match(sql,/alter table public\.reservations add column if not exists table_ids uuid\[\]/i);
  assert.match(sql,/alter table public\.visits add column if not exists table_ids uuid\[\]/i);
  assert.match(sql,/new\.table_id := chosen\[1\]/);
  assert.match(sql,/All selected tables must belong to the same area/);
  assert.match(sql,/where table_ids @> array\[old.id\]/);
  assert.match(sql,/status = 'Active' and voided_at is null/);
  assert.match(app,/\.contains\("table_ids", \[tableId\]\)/, 'VIP conflict lookup includes secondary tables');
  console.log('Multi-table assignments: add/remove, whole room, occupancy, archived tables, area changes, save payload and migration guards passed');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>dom.window.close());
