const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');
const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only',url:'https://example.test/'});
const w=dom.window;
w.t=s=>s;w.escapeHtml=s=>String(s);w.toast=()=>{};w.currentStaffId=()=>null;
w.eval(fs.readFileSync('js/notify.js','utf8')+'\nwindow.seedItems=items=>{_resNotifyItems=items;};');
w._resNotifyClassify=it=>it.ddayAck?'quiet':it.kind;
w._resNotifySlot=()=> 'dday';
let refreshes=0;w._resNotifyRefresh=()=>{refreshes++;};
let fail=false;
w.db={from(){return{update(){return{eq:async()=>({error:fail?new Error('test failure'):null})}}}}};
const rows=[{id:'a',name:'Follow-up guest',kind:'pending'},{id:'b',name:'Deposit guest',kind:'deposit'},{id:'c',name:'Arrival guest',kind:'incoming'}].map(x=>({...x,date:'2026-09-09',time:'13:00',pax:4}));
w.seedItems(rows);
const el=id=>w.document.getElementById(id);
(async()=>{
 w._resNotifyRenderBadge();
 assert.equal(el('res-alert-badge').textContent,'2');assert.equal(el('res-alert-badge-2').textContent,'1');
 assert.equal(el('res-alert-badge-2').closest('button').id,'res-arrival-bell');
 w.toggleResAlertPanel();
 assert.equal(el('res-alert-title').textContent,'Booking follow-ups');
 assert.match(el('res-alert-list').textContent,/Follow-up guest/);assert.match(el('res-alert-list').textContent,/Deposit guest/);
 assert.doesNotMatch(el('res-alert-list').textContent,/Arrival guest/);
 w.toggleResAlertPanel('arrival');
 assert.equal(el('res-alert-title').textContent,'Arrival checks');
 assert.match(el('res-alert-list').textContent,/Arrival guest/);assert.doesNotMatch(el('res-alert-list').textContent,/Follow-up guest|Deposit guest/);
 assert.equal(el('res-alert-bell').getAttribute('aria-expanded'),'false');assert.equal(el('res-arrival-bell').getAttribute('aria-expanded'),'true');
 assert.equal(refreshes,2,'one refresh per opening; no second background fetch loop');
 fail=true;w.console.error=()=>{};await w.resNotifyAckReminder('c');
 assert.match(el('res-alert-list').textContent,/Arrival guest/,'failed acknowledgement restores arrival task');
 fail=false;await w.resNotifyAckReminder('c');
 assert.match(el('res-alert-list').textContent,/No arrival checks due/);assert.equal(el('res-alert-badge-2').classList.contains('hidden'),true);
 assert.equal(el('res-alert-badge').textContent,'2','arrival acknowledgement leaves booking tasks untouched');
 w.toggleResAlertPanel('arrival');assert.equal(el('res-alert-panel').classList.contains('hidden'),true);
 w.toggleResAlertPanel();w.document.body.click();assert.equal(el('res-alert-panel').classList.contains('hidden'),true);
 const app=fs.readFileSync('js/app.js','utf8');w.eval(app.match(/^function toggleBirthdayAlertPanel\([^]*?^}/m)[0]);
 w.toggleResAlertPanel('arrival');w.toggleBirthdayAlertPanel();
 assert.equal(el('res-alert-panel').classList.contains('hidden'),true);assert.equal(el('bd-alert-panel').classList.contains('hidden'),false);
 console.log('Notification icons: independent badges/lists, switching, acknowledgement rollback, empty state and panel dismissal passed');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>w.close());
