// Focused checks on the reservations guest-search wiring.
const fs = require("fs");
const assert = require("assert");
// Normalised, like every other test in this directory. Without it a Windows
// checkout (CRLF working tree, LF in the repo) fails the assertions that
// match on "\n" while CI passes, which reads as a broken feature.
const src = fs.readFileSync("js/app.js", "utf8").replace(/\r\n/g, "\n");
const html = fs.readFileSync("index.html", "utf8");
// config.js is generated by build-config.js and is gitignored, so fall back
// to the template. The parts these tests read are identical in both.
const cfg = fs.readFileSync(
  fs.existsSync("js/config.js") ? "js/config.js" : "js/config.template.js",
  "utf8",
);

let pass = 0, fail = 0;
const check = (name, fn) => {
  try { fn(); pass++; console.log("  ok  " + name); }
  catch (e) { fail++; console.log("  FAIL " + name + " :: " + e.message); }
};

check("day-nav + status chips clear the search", () => {
  ["function moveResDay", "function goToResDate", "function goToResToday", "function filterResByStatus"]
    .forEach((f) => {
      const i = src.indexOf(f);
      assert.ok(i > -1, f + " missing");
      const body = src.slice(i, i + 700);
      assert.ok(body.includes("clearResSearch(true)"), f + " does not clear search");
    });
});

check("loadReservations delegates while a search is active", () => {
  const i = src.indexOf("async function loadReservations()");
  assert.ok(src.slice(i, i + 900).includes("if (resSearchActive) return renderResSearchResults()"));
});

check("search excludes Deleted and spans all dates", () => {
  const i = src.indexOf("async function renderResSearchResults");
  const body = src.slice(i, i + 2000);
  assert.ok(body.includes('.neq("status", "Deleted")'), "Deleted not excluded");
  assert.ok(!body.includes("reservation_date\", date"), "should not filter by day");
  assert.ok(body.includes('.order("reservation_date", { ascending: false })'), "not newest-first");
  assert.ok(body.includes(".limit(RES_SEARCH_ROW_LIMIT)"), "no row cap");
});

check("empty guestIds short-circuits instead of querying .in([])", () => {
  const i = src.indexOf("async function renderResSearchResults");
  assert.ok(src.slice(i, i + 2000).includes("if (resSearchActive.guestIds.length)"));
});

check("phone terms are normalized before lookup", () => {
  const i = src.indexOf("async function lookupResGuests");
  const body = src.slice(i, i + 700);
  assert.ok(body.includes("normalizePhone(term)"));
  assert.ok(body.includes("phone.ilike.%${phoneTerm}%"));
});

check("search term is sanitized (no PostgREST %/, injection)", () => {
  ["function onResSearchInput", "async function runResSearch"].forEach((f) => {
    const i = src.indexOf(f);
    assert.ok(src.slice(i, i + 900).includes("cleanSearchTerm("), f + " not sanitized");
  });
});

check("guest label in the banner is escaped", () => {
  const i = src.indexOf("function renderResSearchChip");
  assert.ok(src.slice(i, i + 900).includes("escapeHtml(resSearchActive.label)"));
});

check("min-length guard exists in both input and submit paths", () => {
  assert.ok(src.includes("const RES_SEARCH_MIN_CHARS = 2;"));
  const i = src.indexOf("async function runResSearch");
  assert.ok(src.slice(i, i + 900).includes("term.length < RES_SEARCH_MIN_CHARS"));
});

check("stale in-flight suggestion is discarded", () => {
  const i = src.indexOf("async function suggestResGuests");
  assert.ok(src.slice(i, i + 700).includes("if (cleanSearchTerm(input.value) !== term) return;"));
});

check("occupancy card hides during search and returns on clear", () => {
  assert.ok(src.slice(src.indexOf("async function renderResSearchResults"), src.indexOf("async function renderResSearchResults") + 600)
    .includes('occupancy.classList.add("hidden")'));
  assert.ok(src.slice(src.indexOf("function clearResSearch"), src.indexOf("function clearResSearch") + 800)
    .includes('occupancy.classList.remove("hidden")'));
});

check("navigating back to the page resets the search", () => {
  const i = src.indexOf('if (page === "reservations")');
  assert.ok(src.slice(i, i + 300).includes("clearResSearch(true)"));
});

check("empty-state copy differs for search vs day", () => {
  const i = src.indexOf("async function renderReservationsTable");
  const body = src.slice(i, i + 800);
  assert.ok(body.includes("No reservations found for this guest"));
  assert.ok(body.includes("No reservations found for this day"));
});

check("CSV export filename reflects an active search", () => {
  const i = src.indexOf("function exportReservations");
  assert.ok(src.slice(i, i + 1800).includes('resSearchActive\n    ? "search-"'));
});

check("markup present with the required ids", () => {
  ["res-search-input", "res-search-suggest", "res-search-chip", "res-search-clear-x", "res-search-wrap"]
    .forEach((id) => assert.ok(html.includes('id="' + id + '"'), id + " missing"));
  const wrap = html.indexOf('id="res-search-wrap"');
  const occ = html.indexOf('id="res-occupancy-summary"');
  const chips = html.indexOf("status-filter-btn");
  assert.ok(chips < wrap && wrap < occ, "search bar not between filter row and occupancy card");
});

check("placeholder is translatable", () => {
  const i = html.indexOf('id="res-search-input"');
  assert.ok(html.slice(i - 400, i + 400).includes("data-i18n-placeholder"));
});

check("new UI strings have Indonesian entries", () => {
  ["Searching...", "No guests found", "Back to day view", "Search results for",
   "all dates", "No reservations found", "1 reservation found",
   "No reservations found for this guest", "Type at least 2 characters to search"]
    .forEach((s) => assert.ok(cfg.includes('"' + s + '"'), "missing ID_DICT: " + s));
  const i18n = fs.readFileSync("js/i18n.js", "utf8");
  assert.ok(i18n.includes("(\\d+) reservations found"), "missing plural pattern");
});

console.log("\n" + pass + " passed, " + fail + " failed");
process.exit(fail ? 1 : 0);
