const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const document=new JSDOM(fs.readFileSync('index.html','utf8')).window.document;
const src=fs.readFileSync('js/app.js','utf8');
let loads=0;
const ctx=vm.createContext({document,Date,console,CURRENT_LANG:'en',TODAY:'2026-09-10',resSelectedDate:'2026-09-10',clearResSearch:()=>{},loadReservations:()=>loads++,toast:()=>{}});
vm.runInContext(src.slice(src.indexOf('let resRangeMode ='),src.indexOf('async function loadReservations()')),ctx);
vm.runInContext(src.slice(src.indexOf('function moveResDay('),src.indexOf('function filterResByStatus(')),ctx);
const range=()=>JSON.parse(JSON.stringify(ctx.reservationDateRange()));
(async()=>{
 assert.deepEqual(range(),{start:'2026-09-10',end:'2026-09-10'});
 ctx.setReservationRangeMode('weekly');assert.deepEqual(range(),{start:'2026-09-07',end:'2026-09-13'});
 ctx.moveResDay(1);assert.deepEqual(range(),{start:'2026-09-14',end:'2026-09-20'});
 ctx.resSelectedDate='2024-02-29';ctx.setReservationRangeMode('monthly');assert.deepEqual(range(),{start:'2024-02-01',end:'2024-02-29'});
 ctx.moveResDay(1);assert.deepEqual(range(),{start:'2024-03-01',end:'2024-03-31'});
 ctx.resSelectedDate='2026-12-31';ctx.moveResDay(1);assert.deepEqual(range(),{start:'2027-01-01',end:'2027-01-31'});
 ctx.resSelectedDate='2026-09-10';ctx.setReservationRangeMode('custom');ctx.setReservationRangeEnd('2026-09-14');ctx.moveResDay(1);
 assert.deepEqual(range(),{start:'2026-09-15',end:'2026-09-19'});
 ctx.setReservationRangeEnd('2026-09-01');assert.equal(range().end,'2026-09-19');
 ctx.goToResToday();assert.deepEqual(range(),{start:'2026-09-10',end:'2026-09-10'});
 const calls=[];ctx.supabaseQuery=async fn=>({data:fn(),error:null});
 const result=await ctx.fetchReservationRangeRows({range:(a,b)=>{calls.push([a,b]);return Array.from({length:a===0?500:2},(_,i)=>({id:a+i}));}});
 assert.equal(result.data.length,502);assert.deepEqual(calls,[[0,499],[500,999]]);
 const filters=[];
 const query={select(){return this},gte(k,v){filters.push([k,'gte',v]);return this},lte(k,v){filters.push([k,'lte',v]);return this},order(){return this},eq(){return this},neq(){return this},range(){return []}};
 Object.assign(ctx,{sweepExpiredDeposits:async()=>{},db:{from:()=>query},resSearchActive:null,resStatusFilter:'all',reservationOnlineOnly:false,sortReservationsByStatus:r=>r,renderReservationsTable:async()=>{},renderResOccupancySummary:async()=>{},syncReservationOnlineFilter:()=>{},allReservations:[]});
 vm.runInContext(src.slice(src.indexOf('async function loadReservations()'),src.indexOf('// Shifts the reservations page')),ctx);
 vm.runInContext('resRangeMode="weekly"',ctx);await ctx.loadReservations();
 assert.ok(filters.some(f=>f[1]==='gte'&&f[2]==='2026-09-07'));
 assert.ok(filters.some(f=>f[1]==='lte'&&f[2]==='2026-09-13'));
 assert.equal(document.getElementById('res-range-mode').value,'weekly');
 console.log('Reservation range boundaries, navigation, pagination and query integration passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
