const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM}=require('jsdom');
const ticketHtml=fs.readFileSync('reservation-ticket.html','utf8');
const w=new JSDOM(ticketHtml,{runScripts:'outside-only',url:'https://demo.test/reservation-ticket.html?t=11111111-1111-4111-a111-111111111111'}).window;
let data={name:'<img src=x onerror=alert(1)>',restaurant:'Restaurant',reference:'RSV-123',date:'2026-09-30',time:'19:00:00',pax:4,area:'Indoor',status:'Reserved'};
w.db={rpc:async()=>({data}),from:()=>({select:()=>({eq:()=>({maybeSingle:async()=>({data:{value:{accent:'#F4EDE3',ink:'#173A60'}}})})})})};w.restaurantName=()=> 'Restaurant';
let brandingLoaded=0;w.initBranding=async()=>{brandingLoaded++;};
w.eval(fs.readFileSync('js/reservation-ticket.js','utf8').replace(/loadReservationTicket\(\);\s*$/,''));
(async()=>{
 await w.loadReservationTicket();
 const el=id=>w.document.getElementById(id);
 assert.equal(brandingLoaded,1);assert.ok(ticketHtml.includes('data-brand-logo="full"'));
 assert.ok(!ticketHtml.includes('id="ticket-restaurant"'));
 assert.equal(w.document.documentElement.style.getPropertyValue('--ticket-header'),'#F4EDE3');
 assert.equal(w.document.documentElement.style.getPropertyValue('--ticket-header-text'),'#173A60');
 const ticketJs=fs.readFileSync('js/reservation-ticket.js','utf8'),ticketCss=fs.readFileSync('css/reservation-ticket.css','utf8');
 assert.match(ticketJs,/fillStyle=ticketHeaderColor/);assert.ok(!/fillRect\(500-width\/2-10/.test(ticketJs));assert.ok(!/header img[^}]*background:white/.test(ticketCss));
 assert.equal(el('ticket-name').textContent,data.name);assert.equal(el('ticket-name').querySelector('img'),null);
 assert.equal(el('ticket-actions').hidden,false);assert.ok(el('ticket-fields').textContent.includes('19:00 WIB'));
 w.setTicketLanguage('id');assert.equal(el('ticket-download').textContent,'Unduh tiket');
 data={...data,status:'Cancelled'};await w.downloadReservationTicket();
 assert.equal(el('ticket-actions').hidden,true);assert.ok(el('ticket-note').textContent.includes('tidak lagi'));
 data=null;await w.loadReservationTicket();assert.equal(el('guest-ticket').hidden,true);assert.equal(el('ticket-retry').hidden,false);
 console.log('Guest ticket renders safely, supports both languages, and blocks downloads after cancellation');
})().catch(e=>{console.error(e);process.exitCode=1;});
