const assert = require('node:assert/strict');
const fs = require('node:fs');
const { JSDOM } = require('jsdom');
const html = fs.readFileSync('index.html', 'utf8');
const app = fs.readFileSync('js/app.js', 'utf8');
const cfg = fs.readFileSync('js/config.template.js', 'utf8');
const lift = (src, name) => src.match(new RegExp(`^(?:async )?function ${name}\\([\\s\\S]*?^}`, 'm'))[0];
const dom = new JSDOM(html, { runScripts: 'outside-only', url: 'http://localhost' });
const w = dom.window;
w.matchMedia = () => ({ matches: false });
w.eval(`var role='admin', currentPage='settings-thresholds'; var t=s=>s;
var currentStaffRole=()=>role;
${cfg.slice(cfg.indexOf('const STAFF_ALLOWED_PAGES'),cfg.indexOf('function applyRoleToNav'))}
${fs.readFileSync('js/settings-navigation.js','utf8')}`);

const d = w.document;
const pageOf = id => d.getElementById(id).closest('.page-section').id;
assert.equal(pageOf('set-high-total'), 'page-settings-spending');
assert.equal(pageOf('set-spv'), 'page-settings-membership');
assert.equal(pageOf('set-res-paused'), 'page-settings-thresholds');
assert.equal(pageOf('rff-deposit-basis'), 'page-settings-financial');
assert.equal(pageOf('rff-bank'), 'page-settings-payments');
assert.equal(pageOf('management-threshold-settings'), 'page-settings-outlook');
const ids = [...d.querySelectorAll('[id]')].map(el=>el.id);
assert.equal(ids.length,new Set(ids).size,'no duplicated control IDs');
w.renderSettingsNavigation('settings-thresholds');
assert.equal(d.querySelectorAll('.settings-child').length,7);
assert.equal(d.querySelectorAll('#page-settings-thresholds .settings-local-tabs button').length,4);
assert.equal(d.querySelectorAll('#page-settings-spending .settings-local-tabs').length,0);
w.toggleSettingsNavigation(); assert.equal(d.getElementById('settings-children').hidden,true);
w.toggleSettingsNavigation(); assert.equal(d.getElementById('settings-children').hidden,false);
w.toggleSidebarSize(); assert.equal(w.localStorage.getItem('intoch.sidebarCompact'),'true');
assert.equal(d.getElementById('settings-children').hidden,true);
w.toggleSettingsNavigation(); assert.equal(d.getElementById('settings-children').hidden,false);
w.settingsNavigationChanged('settings-spending'); assert.equal(d.getElementById('settings-children').hidden,true);
w.toggleSidebarDrawer(true); assert.equal(d.getElementById('sidebar-backdrop').hidden,false);
w.settingsNavigationChanged('settings-spending'); assert.equal(d.getElementById('sidebar-backdrop').hidden,true);
w.eval("currentPage='settings-spending'");
d.getElementById('page-settings-spending').classList.add('active');
w.settingsCaptureBaseline(d.getElementById('page-settings-spending'));
d.getElementById('set-high-total').value='1000000';
assert.equal(w.settingsIsDirty(),true);
w.confirm=()=>false; assert.equal(w.settingsMayNavigate(),false,'cancel preserves unsaved edits');
w.settingsCaptureBaseline(d.getElementById('set-spending-tracking').closest('.card'));
assert.equal(w.settingsIsDirty(),true,'saving tracking must not clear dirty spending rules');
w.settingsCaptureBaseline(d.getElementById('set-high-total').closest('.card'));
assert.equal(w.settingsIsDirty(),false);
w.eval("role='manager'"); w.renderSettingsNavigation('settings-spending');
assert.equal(d.querySelectorAll('.settings-child').length,6);
assert.ok(!d.getElementById('settings-children').textContent.includes('Staff & Access'));
for(const role of ['staff','finance','owner']) {
  w.eval(`role='${role}'`); w.renderSettingsNavigation('settings-spending');
  assert.equal(d.querySelectorAll('.settings-child').length,0,role+' cannot access settings');
}

w.eval(`var APP_SETTINGS={reservation_form:{show_notes:true, welcome_text:'Saved welcome',bank_details:'Saved bank',wa_number:'62811',deposit_basis:'area',deposit_free_pax:1,deposit_regular_max_pax:20,unknown:'keep'}, financial_tracking:{deposit_enabled:true,spending_enabled:true}};
var isManagerOrAdmin=()=>['admin','manager'].includes(role), loader=()=>{}, messages=[], toast=s=>messages.push(s), CURRENT_LANG='en';
var RESERVATION_WELCOME_MAX=160, RESERVATION_NOTES_PLACEHOLDER_MAX=160, RESERVATION_PAX_REQUEST_MAX=160, RESERVATION_BANK_MAX=400;
var writes=[], empty=false; var supabaseQuery=fn=>fn();
var db={from:()=>({upsert:row=>({select:async()=>{writes.push(row);return {data:empty?[]:[row]};}}),update:row=>({eq:()=>({select:async()=>{writes.push(row);return {data:empty?[]:[row]};}})})})};
var renderReservationFormFields=()=>{}, applyFinancialTrackingUI=()=>{};
${lift(app,'saveReservationFormFields')}
${lift(app,'financialTrackingSettings')}
${lift(app,'saveFinancialTrackingSettings')}`);
(async()=>{
  w.eval("role='admin'");
  d.getElementById('rff-deposit-basis').value='pax';
  d.getElementById('rff-deposit-free-pax').value='3';
  d.getElementById('rff-deposit-max-pax').value='25';
  d.getElementById('rff-bank').value='Unsaved bank';
  d.getElementById('rff-welcome').value='Unsaved welcome';
  await w.saveReservationFormFields('deposits');
  assert.equal(w.writes.at(-1).value.deposit_free_pax,3);
  assert.equal(w.writes.at(-1).value.bank_details,'Saved bank');
  assert.equal(w.writes.at(-1).value.welcome_text,'Saved welcome');
  assert.equal(w.writes.at(-1).value.unknown,'keep');
  d.getElementById('rff-deposit-free-pax').value='999';
  await w.saveReservationFormFields('payments');
  assert.equal(w.writes.at(-1).value.bank_details,'Unsaved bank');
  assert.equal(w.writes.at(-1).value.deposit_free_pax,3);
  await w.saveReservationFormFields();
  assert.equal(w.writes.at(-1).value.welcome_text,'Unsaved welcome');
  assert.equal(w.writes.at(-1).value.deposit_free_pax,3);
  const before=w.writes.length;
  await w.saveReservationFormFields('deposits');
  assert.equal(w.writes.length,before,'invalid deposit rule blocked');
  w.eval("role='manager'");
  d.getElementById('rff-bank').value='Forbidden bank';
  d.getElementById('rff-wa').value='628222';
  await w.saveReservationFormFields('payments');
  assert.equal(w.writes.at(-1).value.bank_details,'Unsaved bank','manager cannot alter bank instructions');
  assert.equal(w.writes.at(-1).value.wa_number,'628222','existing manager contact permission preserved');
  d.getElementById('set-deposit-tracking').checked=false;
  d.getElementById('set-spending-tracking').checked=false;
  await w.saveFinancialTrackingSettings('deposit_enabled');
  assert.equal(w.writes.at(-1).value.spending_enabled,true,'deposit switch does not save spending switch');
  w.eval('empty=true');
  await w.saveFinancialTrackingSettings('spending_enabled');
  assert.equal(w.APP_SETTINGS.financial_tracking.spending_enabled,true,'empty returned rows are not success');
  dom.window.close();
  console.log('Settings navigation, responsive controls, roles and isolated saves passed');
})().catch(error=>{dom.window.close(); console.error(error);process.exitCode=1;});
