const fs=require('fs'),assert=require('node:assert/strict');const {JSDOM}=require('jsdom');
const w=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'outside-only',url:'https://example.com'}).window;
w.t=s=>s;w.STAFF_SESSION_KEY='staff-test';
const source=fs.readFileSync('js/config.template.js','utf8');w.eval(source.slice(source.indexOf('function getStaffSession()'),source.indexOf('// RESERVATION PAGE APPEARANCE')));
for(const role of ['owner','admin','manager','staff']){
 w.setStaffSession({id:'1',role});
 assert.equal(w.hasAccess('dashboard'),true);
 assert.equal(w.hasAccess('reservation-outlook'),role==='admin'||role==='owner');
 assert.equal(w.hasAccess('staff-dashboard'),role==='admin');
 assert.equal(w.hasAccess('settings-staff'),role==='admin');
 assert.equal(w.canManagePaymentSettings(),role==='admin');
 assert.equal(w.canWaiveDeposit(),role==='admin'||role==='manager');
 assert.equal(w.hasAccess('reports'),role!=='staff');
 assert.equal(w.hasAccess('guests'),role!=='owner');
 assert.equal(w.hasAccess('broadcast'),role==='admin'||role==='manager');
 w.applyRoleToNav();assert.equal(w.document.getElementById('rff-bank').disabled,role!=='admin');
}
w.eval(fs.readFileSync('js/staff-auth.js','utf8'));
// Exercise the actual demo presentation exception with the real role policy.
const demoSource=fs.readFileSync('js/demo.js','utf8');
w.eval(demoSource.slice(demoSource.indexOf('function demoEnabled()'),demoSource.indexOf('function demoRoute(')));
w.INTOCH_DEMO_TOUR_ENV={origins:['https://example.com'],supabaseUrl:'https://playground.supabase.co'};
w.SUPABASE_URL='https://playground.supabase.co';w.document.documentElement.classList.add('demo-mode');
w.setStaffSession({id:'demo-staff',role:'staff'});
assert.equal(w.hasAccess('reports'),false,'Unverified demo cannot expose Reports');
w.demoSessionReady(w.getStaffSession());assert.equal(w.hasAccess('reports'),true,'Verified playground Staff sees Reports');
w.applyRoleToNav();assert.equal(w.document.querySelector('[data-nav="reports"]').style.display,'');
assert.equal(w.hasAccess('broadcast'),false,'Demo does not grant campaign access');
w.SUPABASE_URL='https://client.supabase.co';assert.equal(w.hasAccess('reports'),false,'Other project remains restricted');
w.SUPABASE_URL='https://playground.supabase.co';w.INTOCH_DEMO_TOUR_ENV.origins=[];assert.equal(w.hasAccess('reports'),false,'Other origin remains restricted');
w.INTOCH_DEMO_TOUR_ENV.origins=['https://example.com'];w.document.documentElement.classList.remove('demo-mode');assert.equal(w.hasAccess('reports'),false,'Ordinary Staff remains restricted');
w.document.documentElement.classList.add('demo-mode');w.demoSessionReady(null);assert.equal(w.hasAccess('reports'),false,'Teardown removes presentation exception');
w.document.documentElement.classList.remove('demo-mode');
w.setStaffSession({id:'fo',role:'staff',can_waive_deposit:true});assert.equal(w.canWaiveDeposit(),true);
w.setStaffSession({id:'owner',role:'owner',can_waive_deposit:true});assert.equal(w.canWaiveDeposit(),false);
(async()=>{
 w.setStaffSession({id:'forged',role:'admin'});
 w.db={auth:{getUser:async()=>({error:Error('No JWT')}),signOut:async()=>{} }};
 assert.equal(await w.restoreVerifiedStaffSession(),null);assert.equal(w.getStaffSession(),null);
 const profile={id:'actual',role:'staff',is_active:true};
 const query={select(){return this},eq(){return this},maybeSingle:async()=>({data:profile})};
 w.db={rpc:async()=>({data:true}),auth:{getUser:async()=>({data:{user:{id:'auth-id'}}})},from:()=>query};
 await w.restoreVerifiedStaffSession();assert.equal(w.getStaffSession().role,'staff');
 w.db.rpc=async()=>({data:true});await w.refreshDepositWaiverPermission();assert.equal(w.canWaiveDeposit(),true);
 w.db.rpc=async()=>({data:false});await w.refreshDepositWaiverPermission();assert.equal(w.canWaiveDeposit(),false);
 w.setStaffSession({...w.getStaffSession(),can_waive_deposit:true});w.db.rpc=async()=>{throw Error('offline')};await w.refreshDepositWaiverPermission();assert.equal(w.canWaiveDeposit(),false);
 const app=fs.readFileSync('js/app.js','utf8');w.CURRENT_LANG='en';
 w.eval(app.match(/^function updateStaffWaiverControl\([^]*?^}/m)[0]);
 w.document.getElementById('staff-form-role').value='staff';w.updateStaffWaiverControl();assert.equal(w.document.getElementById('staff-form-waiver-wrap').classList.contains('hidden'),false);
 w.document.getElementById('staff-form-role').value='manager';w.updateStaffWaiverControl();assert.equal(w.document.getElementById('staff-form-waiver-wrap').classList.contains('hidden'),true);
 assert.equal(w.staffAuthEmail(' Rina '),'rina@staff.intoch.invalid');
 console.log('Role navigation, admin payment controls and verified session restoration passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
