const assert = require('node:assert/strict');
const fs = require('node:fs');
const { PGlite } = require('@electric-sql/pglite');
const sql = fs.readFileSync('migrations/20260909_timed_table_capacity.sql','utf8');
const db = new PGlite();
(async () => {
 await db.exec(`
 create role anon; create role authenticated;
 create table app_settings(key text primary key,value jsonb);
 insert into app_settings values ('reservation_hours','{"max_pax":100,"default_duration_minutes":180}');
 create function get_setting(k text) returns jsonb language sql stable as $$select value from app_settings where key=k$$;
 create function reservation_hours_for(d date) returns jsonb language sql as $$select '{"open":"00:00","close":"23:59","closed":false}'::jsonb$$;
 create table areas(id uuid primary key default gen_random_uuid(),name text,capacity integer,min_pax integer,min_spend numeric,deposit_amount numeric,is_bookable_online boolean default true);
 create table tables(id uuid primary key default gen_random_uuid(),area_id uuid references areas,name text,capacity integer,is_active boolean default true);
 create table guests(id uuid primary key default gen_random_uuid(),name text,phone text unique,company text,booking_alias text,updated_at timestamptz);
 create table reservations(id uuid primary key default gen_random_uuid(),guest_id uuid references guests,
 reservation_date date not null,reservation_time time not null,end_time time,pax integer not null,status text default 'Reserved',
 assigned_area uuid references areas,table_id uuid,table_ids uuid[] not null default '{}',deleted_at timestamptz,
 reservation_source text,notes text,booking_name text,deposit_required boolean,deposit_expected numeric,
 deposit_rule_note text,waitlist_reason text,deposit_due_at timestamptz);
 `);
 await db.exec(sql);
 await db.exec(sql); // rerunnable upgrade
 const flow = fs.readFileSync('migrations/20260910_reservation_deposit_flow.sql','utf8');
 await db.exec(flow); await db.exec(flow);
 const {rows:[area]} = await db.query("insert into areas(name,capacity) values ('Outdoor',65) returning id");
 const {rows:tables} = await db.query("insert into tables(area_id,name,capacity) select $1,'T'||n,5 from generate_series(1,13)n returning id",[area.id]);
 const {rows:[day]} = await db.query("select (current_date+1)::text as date");
 const date=day.date;
 const q = (s,p=[]) => db.query(s,p);
 const cap = async (time='13:00',minutes=180) => (await q('select * from reservation_capacity($1,$2::date+$3::time,$2::date+$3::time+make_interval(mins=>$4))',[area.id,date,time,minutes])).rows[0];
 const add = async ({time='13:00',end='16:00',pax=40,ids=tables.slice(0,8).map(t=>t.id),status='Reserved',buffer=0,exclusive=false}={}) => (await q('insert into reservations(assigned_area,reservation_date,reservation_time,end_time,pax,table_ids,status,block_buffer_minutes,exclusive_area) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning id',[area.id,date,time,end,pax,ids,status,buffer,exclusive])).rows[0].id;
 const clear = () => db.exec('delete from reservations; delete from guests;');
 let event=await add();
 assert.equal((await cap()).available_capacity,25,'40 selected seats leaves 25');
 assert.equal((await cap('12:00')).available_capacity,25,'visit beginning earlier overlaps the event');
 assert.equal((await cap('16:00')).available_capacity,65,'end is exclusive');
 assert.equal((await cap('10:00')).available_capacity,65,'visit ending at start fits');
 await assert.rejects(add({pax:5,ids:[tables[0].id]}),/already reserved/,'same table cannot be booked twice');
 await add({pax:10,ids:[],end:'14:00'});
 assert.equal((await cap()).available_capacity,15,'unassigned bookings consume capacity');
 await add({pax:10,ids:[],time:'14:00',end:'15:00'});
 assert.equal((await cap()).available_capacity,15,'nonoverlapping unassigned groups count at peak, not their sum');
 await assert.rejects(add({pax:20,ids:[]}),/remaining capacity/);
 await q("update reservations set status='Cancelled' where id=$1",[event]);
 assert.equal((await cap()).available_capacity,55,'cancelled event releases tables');
 await clear(); await add({pax:40,ids:tables.slice(0,9).map(t=>t.id)});
 assert.equal((await cap()).available_capacity,20,'selected seats, not just pax');
 await clear(); await add({buffer:30});
 assert.equal((await cap('09:00',210)).available_capacity,65,'visit ends exactly at buffer start');
 assert.equal((await cap('10:00')).available_capacity,25,'buffer overlaps visit');
 await clear(); await add({status:'Waitlist'}); assert.equal((await cap()).available_capacity,65);
 await clear(); await add({status:'Incoming'}); assert.equal((await cap()).available_capacity,25);
 await clear(); await add({exclusive:true}); assert.equal((await cap()).available_capacity,0);
 await clear(); await add({ids:tables.map(t=>t.id)}); assert.equal((await cap()).available_capacity,0,'all tables selected holds all capacity');
 await clear();
 // The same exact table must be free for the entire visit, even if another
 // table becomes available halfway through.
 await add({pax:5,ids:[tables[0].id],end:'14:00'});
 await add({pax:5,ids:[tables[1].id],time:'14:00',end:'15:00'});
 assert.equal((await cap()).available_capacity,55);
 await clear();
 await q("update app_settings set value=value||'{\"default_duration_minutes\":120}' where key='reservation_hours'");
 event=await add({end:null});
 assert.equal((await q('select booking_duration_minutes as n from reservations where id=$1',[event])).rows[0].n,120);
 await q("update app_settings set value=value||'{\"default_duration_minutes\":180}' where key='reservation_hours'");
 assert.equal((await cap('15:00')).available_capacity,65,'existing booking keeps its snapshot');
 await clear();
 event=await add({time:'23:00',end:null});
 assert.equal((await q('select available_capacity from reservation_capacity($1,$2::date+1,$2::date+1+interval \'1 hour\')',[area.id,date])).rows[0].available_capacity,25,'overnight defaults carry into next date');
 await clear(); await add();
 const book = async (pax,phone,time='13:00') => (await q("select create_public_reservation('Test Guest',$1,$2,$3,$4,null,$5,null) as result",[phone,pax,date,time,area.id])).rows[0].result;
 let result=await book(30,'08111111111'); assert.equal(result.status,'Waitlist'); assert.equal(result.deposit_required,false);
 assert.equal((await cap()).available_capacity,25,'waitlist holds no capacity');
 result=await book(10,'08222222222'); assert.equal(result.ok,true);
 assert.equal((await cap()).available_capacity,15);
 result=await book(20,'08333333333'); assert.equal(result.status,'Waitlist','already-open form waitlists without overbooking');
 result=await book(30,'08444444444','16:00'); assert.equal(result.ok,true,'event does not block the whole date');
 const slots=(await q('select * from area_slot_availability($1)',[date])).rows;
 assert.equal(slots.length,24);
 assert.deepEqual(Object.keys(slots[0]).sort(),['area_id','available_pax','duration_minutes','exclusive_block','slot_time','total_capacity'].sort(),'public response contains no guest data');
 await clear();
 await q('update tables set capacity=2 where area_id=$1',[area.id]);
 result=await book(30,'08555555555');
 assert.equal(result.status,'Waitlist','a party exceeding actual table seats must not be auto-confirmed');
 assert.equal(result.waitlist_reason,'over_capacity');
 await q('update tables set capacity=5 where area_id=$1',[area.id]);
 await q("insert into areas(name,capacity) values ('Indoor',65)");
 result=await book(70,'08666666666'); assert.equal(result.status,'Waitlist','oversized request remains possible for an empty room');
 assert.equal((await cap()).available_capacity,65);
 await clear();
 event=await add({pax:5,ids:[tables[0].id],end:'14:00'});
 const other=await add({pax:5,ids:[tables[1].id],time:'14:00',end:'15:00'});
 await assert.rejects(q('update reservations set reservation_time=\'13:30\',table_ids=$1 where id=$2',[[tables[0].id],other]),/already reserved/,'editing also protects specific tables');
 await q("update reservations set status='Completed' where id=$1",[event]);
 await q('update reservations set reservation_time=\'13:30\',table_ids=$1 where id=$2',[[tables[0].id],other]);
 assert.equal((await cap()).available_capacity,60,'completion releases the previous hold');

 await clear();
 await q('update areas set deposit_amount=50000 where id=$1',[area.id]);
 event=await add({pax:61,ids:[]});
 result=await book(10,'08777777777');
 assert.equal(result.status,'Waitlist'); assert.equal(result.deposit_required,false);
 assert.equal(result.deposit_expected,50000); assert.equal(result.deposit_due_at,null);
 let booking=(await q('select * from reservations where id=$1',[result.reservation_id])).rows[0];
 assert.equal(booking.is_large_party,false);
 await assert.rejects(q("update reservations set status='Reserved' where id=$1",[booking.id]),/remaining capacity/,'staff cannot accept before capacity is available');
 await q("update reservations set status='Cancelled' where id=$1",[event]);
 await q("update reservations set status='Reserved' where id=$1",[booking.id]);
 booking=(await q('select * from reservations where id=$1',[booking.id])).rows[0];
 assert.equal(booking.status,'Incoming'); assert.equal(booking.deposit_required,true); assert.ok(booking.deposit_due_at);
 await clear();
 await q('update areas set deposit_amount=null where id=$1',[area.id]);
 result=await book(110,'08888888888');
 booking=(await q('select * from reservations where id=$1',[result.reservation_id])).rows[0];
 assert.equal(booking.is_large_party,true); assert.equal(booking.status,'Waitlist'); assert.equal(booking.deposit_required,false);
 await clear();
 event=await add({pax:65,ids:[]});
 result=await book(10,'08999999999');
 assert.equal(result.status,'Waitlist'); assert.equal(result.deposit_required,false);
 await q("update reservations set status='Cancelled' where id=$1",[event]);
 await q("update reservations set status='Reserved' where id=$1",[result.reservation_id]);
 assert.equal((await q('select status from reservations where id=$1',[result.reservation_id])).rows[0].status,'Reserved','no-deposit area needs no invoice');
 await db.exec('set role anon');
 await q('select * from area_slot_availability($1)',[date]);
 await assert.rejects(cap(),/permission denied/,'private calculator cannot be queried by anonymous users');
 await db.exec('reset role');
 console.log('Timed capacity SQL: migration rerun, table holds, buffers, peak unassigned pax, overnight visits, duration snapshots, public submission and permissions passed');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.close());
