-- ============================================================
-- Membership merge: tables + business-rule functions
-- Applied to staging 2026-07-05 (verified). Run on prod at cutover.
-- ============================================================

CREATE TABLE members (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  member_number VARCHAR NOT NULL UNIQUE,
  member_type VARCHAR NOT NULL CHECK (member_type IN ('Company','Family')),
  full_name VARCHAR NOT NULL,
  phone_number VARCHAR NOT NULL,
  guest_id UUID UNIQUE REFERENCES guests(id) ON DELETE SET NULL,
  total_stickers INTEGER NOT NULL DEFAULT 0 CHECK (total_stickers >= 0),
  available_vouchers INTEGER NOT NULL DEFAULT 0 CHECK (available_vouchers >= 0),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE member_transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  member_id BIGINT NOT NULL REFERENCES members(id),
  visit_id UUID REFERENCES visits(id) ON DELETE SET NULL,
  transaction_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cashier_name VARCHAR,
  created_by UUID REFERENCES staff_users(id),
  transaction_amount NUMERIC NOT NULL CHECK (transaction_amount > 0),
  qualified_sticker BOOLEAN NOT NULL DEFAULT false,
  sticker_round INTEGER,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE member_vouchers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  member_id BIGINT NOT NULL REFERENCES members(id),
  voucher_type VARCHAR NOT NULL,
  voucher_amount NUMERIC NOT NULL,
  issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  redeemed BOOLEAN NOT NULL DEFAULT false,
  redeemed_at TIMESTAMPTZ,
  redeemed_by UUID REFERENCES staff_users(id)
);

CREATE INDEX idx_member_txn_member ON member_transactions (member_id);
CREATE INDEX idx_member_txn_date ON member_transactions (transaction_date);
CREATE INDEX idx_member_vouchers_member ON member_vouchers (member_id);
CREATE INDEX idx_member_vouchers_open ON member_vouchers (member_id) WHERE NOT redeemed;
CREATE INDEX idx_members_guest ON members (guest_id);

CREATE TRIGGER members_updated_at BEFORE UPDATE ON members FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- One visit can award at most one membership transaction (idempotency)
CREATE UNIQUE INDEX ux_member_txn_visit ON member_transactions (visit_id) WHERE visit_id IS NOT NULL;

-- Family : min 300k/visit = 1 sticker, 5 stickers = 100k voucher, max 15 stickers
-- Company: min 2M/visit  = 1 sticker, 5 stickers = 500k voucher, no cap
CREATE OR REPLACE FUNCTION add_member_transaction(
  p_member_id BIGINT,
  p_amount NUMERIC,
  p_date TIMESTAMPTZ DEFAULT NOW(),
  p_notes TEXT DEFAULT NULL,
  p_created_by UUID DEFAULT NULL,
  p_cashier_name VARCHAR DEFAULT NULL,
  p_visit_id UUID DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
  m RECORD;
  v_min NUMERIC; v_voucher_amount NUMERIC; v_cap INTEGER;
  v_qualified BOOLEAN;
  v_reason TEXT;
  v_new_total INTEGER;
  v_round INTEGER;
  v_vouchers_to_issue INTEGER := 0;
  v_txn_id BIGINT;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Transaction amount must be positive';
  END IF;

  SELECT * INTO m FROM members WHERE id = p_member_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Member % not found', p_member_id;
  END IF;
  IF NOT m.is_active THEN
    RAISE EXCEPTION 'Member % is inactive', m.member_number;
  END IF;

  -- Same visit already recorded? Skip silently (idempotent).
  IF p_visit_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM member_transactions WHERE visit_id = p_visit_id
  ) THEN
    RETURN jsonb_build_object('skipped', true, 'reason', 'visit_already_recorded');
  END IF;

  IF m.member_type = 'Family' THEN
    v_min := 300000; v_voucher_amount := 100000; v_cap := 15;
  ELSE
    v_min := 2000000; v_voucher_amount := 500000; v_cap := NULL;
  END IF;

  -- Why did (or didn't) this earn a sticker? (used for Indonesian toasts)
  IF p_amount < v_min THEN
    v_qualified := FALSE; v_reason := 'below_minimum';
  ELSIF v_cap IS NOT NULL AND m.total_stickers >= v_cap THEN
    v_qualified := FALSE; v_reason := 'cap_reached';
  ELSE
    v_qualified := TRUE; v_reason := 'earned';
  END IF;
  v_new_total := m.total_stickers + CASE WHEN v_qualified THEN 1 ELSE 0 END;
  v_round := CASE WHEN v_qualified THEN (m.total_stickers / 5) + 1 ELSE NULL END;

  IF v_qualified THEN
    v_vouchers_to_issue := (v_new_total / 5) - (m.total_stickers / 5);
  END IF;

  INSERT INTO member_transactions
    (member_id, visit_id, transaction_date, cashier_name, created_by, transaction_amount, qualified_sticker, sticker_round, notes)
  VALUES
    (p_member_id, p_visit_id, p_date, p_cashier_name, p_created_by, p_amount, v_qualified, v_round, p_notes)
  RETURNING id INTO v_txn_id;

  IF v_vouchers_to_issue > 0 THEN
    INSERT INTO member_vouchers (member_id, voucher_type, voucher_amount, issued_at)
    SELECT p_member_id, m.member_type, v_voucher_amount, p_date
    FROM generate_series(1, v_vouchers_to_issue);
  END IF;

  UPDATE members
  SET total_stickers = v_new_total,
      available_vouchers = available_vouchers + v_vouchers_to_issue
  WHERE id = p_member_id;

  RETURN jsonb_build_object(
    'transaction_id', v_txn_id,
    'earned_sticker', v_qualified,
    'sticker_reason', v_reason,
    'new_total_stickers', v_new_total,
    'vouchers_issued', v_vouchers_to_issue,
    'at_sticker_cap', v_cap IS NOT NULL AND v_new_total >= v_cap
  );
END;
$$;

CREATE OR REPLACE FUNCTION redeem_member_voucher(
  p_voucher_id BIGINT,
  p_redeemed_by UUID DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql AS $$
DECLARE
  v_member_id BIGINT;
BEGIN
  UPDATE member_vouchers
  SET redeemed = true, redeemed_at = NOW(), redeemed_by = p_redeemed_by
  WHERE id = p_voucher_id AND redeemed = false
  RETURNING member_id INTO v_member_id;

  IF v_member_id IS NULL THEN
    RAISE EXCEPTION 'Voucher not found or already redeemed';
  END IF;

  UPDATE members
  SET available_vouchers = GREATEST(available_vouchers - 1, 0)
  WHERE id = v_member_id;

  RETURN jsonb_build_object('ok', true, 'member_id', v_member_id);
END;
$$;
